// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_rest_ from "./routes/[...rest].tsx";
import * as $_version_methods from "./routes/[version]/methods.tsx";
import * as $_version_methods_name_ from "./routes/[version]/methods/[name].tsx";
import * as $_version_tl_enums from "./routes/[version]/tl/enums.tsx";
import * as $_version_tl_enums_name_ from "./routes/[version]/tl/enums/[name].tsx";
import * as $_version_tl_functions from "./routes/[version]/tl/functions.tsx";
import * as $_version_tl_functions_name_ from "./routes/[version]/tl/functions/[name].tsx";
import * as $_version_tl_types from "./routes/[version]/tl/types.tsx";
import * as $_version_tl_types_name_ from "./routes/[version]/tl/types/[name].tsx";
import * as $_version_types_name_ from "./routes/[version]/types/[name].tsx";
import * as $_version_xtypes_ from "./routes/[version]/xtypes_.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $errors from "./routes/errors.tsx";
import * as $index from "./routes/index.tsx";
import * as $methods from "./routes/methods.tsx";
import * as $source_map from "./routes/source-map.tsx";
import * as $types from "./routes/types.tsx";
import * as $versions from "./routes/versions.tsx";
import * as $x from "./routes/x.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...rest].tsx": $_rest_,
    "./routes/[version]/methods.tsx": $_version_methods,
    "./routes/[version]/methods/[name].tsx": $_version_methods_name_,
    "./routes/[version]/tl/enums.tsx": $_version_tl_enums,
    "./routes/[version]/tl/enums/[name].tsx": $_version_tl_enums_name_,
    "./routes/[version]/tl/functions.tsx": $_version_tl_functions,
    "./routes/[version]/tl/functions/[name].tsx": $_version_tl_functions_name_,
    "./routes/[version]/tl/types.tsx": $_version_tl_types,
    "./routes/[version]/tl/types/[name].tsx": $_version_tl_types_name_,
    "./routes/[version]/types/[name].tsx": $_version_types_name_,
    "./routes/[version]/xtypes_.tsx": $_version_xtypes_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/errors.tsx": $errors,
    "./routes/index.tsx": $index,
    "./routes/methods.tsx": $methods,
    "./routes/source-map.tsx": $source_map,
    "./routes/types.tsx": $types,
    "./routes/versions.tsx": $versions,
    "./routes/x.tsx": $x,
  },
  islands: {
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
